apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
      release: "0-5"
  template:
    metadata:
      labels:
        app: webapp
        release: "0-5"
    spec:
      containers:
      - name: webapp
        image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: queue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queue
      release: "1"
  template:
    metadata:
      labels:
        app: queue
        release: "1"
    spec:
      containers:
      - name: queue
        image: richardchesterwood/k8s-fleetman-queue:release1